### PR TITLE
Jetbrains-Products

### PR DESCRIPTION
**Pull request by danielroehrig**
* Added Clion Icon
* Changed phpStorm icon to Mark Shropshire's version (adapted)

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by Foggalong** [comment]
What's going on here? The pull deletes 100s of icons :/

**Comment by danielroehrig** [comment]
How? I just added two icons.

**Comment by Foggalong** [comment]
Look at your diff!

**Comment by snwh** [comment]
This makes a lot of unnecessary changes. However, I fixed the missing autogen.sh, which I didn't pick up on.

**Comment by snwh** [comment]
If you'd like to open a pull request with just the icon addition, feel free.

**Comment by danielroehrig** [comment]
I deleted the icons from the "Moka"-folder as I thought they would be automatically generated from the SVGs. But the folder was not in the .gitignore file so that should explain the missing icons. Maybe I've gone to far. Also, I didn't find the autogen.sh file so I created one. But I will just fork again and add the two icons. Sorry for the hiccup.

**Comment by snwh** [comment]
The autogen.sh was accidentally omitted by my gitignore without my noticing, so you did bring that to my attention at least

**Pull request closed without merging**
