### PR TITLE
Added mattermost-desktop icon

### PR DESCRIPTION
**Pull request by o-schneider**
Add the icon for mattermost-desktop (mattermost.org)

### CODE REVIEW

**Comment by snwh** [comment]
You'll need to add the drop shadow to the pictogram (the mattermost logo), which is just a 20% opacity black version of the pictogram moved down 1px and below it.

**Comment by o-schneider** [comment]
Is it better like this ? :)

**Comment by snwh** [comment]
Almost, exactly but it needs to be exactly 1px from the bottom of each pictogram.

**Comment by o-schneider** [comment]
Oh god, I put two pixels. My bad... :s
I thought the others should be proportional. Checked on one of your icons and did the same.
Just pushed a new commit. Let me know if there's still something to do.i :)

**Comment by snwh** [comment]
Looks good :+1:

**Pull request merged**
